// Auto-generated by scripts/generate-version.ts
// DO NOT EDIT MANUALLY

export const APP_VERSION = 'v0.1-b6a44f4';
export const APP_VERSION_FULL = 'v0.1-b6a44f4 (125 commits, main)';
export const APP_VERSION_PREFIX = 'v0.1';
export const APP_GIT_HASH = 'b6a44f4';
export const APP_COMMIT_COUNT = '125';
export const APP_BRANCH = 'main';
