// Auto-generated by scripts/generate-version.ts
// DO NOT EDIT MANUALLY

export const APP_VERSION = 'v0.1-2f463bb';
export const APP_VERSION_FULL = 'v0.1-2f463bb (290 commits, main)';
export const APP_VERSION_PREFIX = 'v0.1';
export const APP_GIT_HASH = '2f463bb';
export const APP_COMMIT_COUNT = '290';
export const APP_BRANCH = 'main';
