// Auto-generated by scripts/generate-version.ts
// DO NOT EDIT MANUALLY

export const APP_VERSION = 'v0.1-017643f';
export const APP_VERSION_FULL = 'v0.1-017643f (72 commits, main)';
export const APP_VERSION_PREFIX = 'v0.1';
export const APP_GIT_HASH = '017643f';
export const APP_COMMIT_COUNT = '72';
export const APP_BRANCH = 'main';
