// Auto-generated by scripts/generate-version.ts
// DO NOT EDIT MANUALLY

export const APP_VERSION = 'v0.2-b747990';
export const APP_VERSION_FULL = 'v0.2-b747990 (301 commits, main)';
export const APP_VERSION_PREFIX = 'v0.2';
export const APP_GIT_HASH = 'b747990';
export const APP_COMMIT_COUNT = '301';
export const APP_BRANCH = 'main';
