#!/usr/bin/env tsx
/**
 * Generate version based on git commit hash
 * Format: v0.1-{shortGitHash}
 * Example: v0.1-abcd1234
 */

import { execSync } from 'child_process';
import { writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const VERSION_FILE = join(__dirname, '../src/lib/version-generated.ts');
const VERSION_PREFIX = 'v0.1';

try {
  // Get short git hash (7 characters)
  const gitHash = execSync('git rev-parse --short=7 HEAD', {
    encoding: 'utf-8',
    stdio: ['pipe', 'pipe', 'ignore']
  }).trim();

  // Get commit count for build number
  const commitCount = execSync('git rev-list --count HEAD', {
    encoding: 'utf-8',
    stdio: ['pipe', 'pipe', 'ignore']
  }).trim();

  // Get branch name
  const branch = execSync('git rev-parse --abbrev-ref HEAD', {
    encoding: 'utf-8',
    stdio: ['pipe', 'pipe', 'ignore']
  }).trim();

  const version = `${VERSION_PREFIX}-${gitHash}`;
  const fullVersion = `${version} (${commitCount} commits, ${branch})`;

  // Generate TypeScript file
  const content = `// Auto-generated by scripts/generate-version.ts
// DO NOT EDIT MANUALLY

export const APP_VERSION = '${version}';
export const APP_VERSION_FULL = '${fullVersion}';
export const APP_VERSION_PREFIX = '${VERSION_PREFIX}';
export const APP_GIT_HASH = '${gitHash}';
export const APP_COMMIT_COUNT = '${commitCount}';
export const APP_BRANCH = '${branch}';
`;

  // Ensure directory exists
  mkdirSync(join(__dirname, '../src/lib'), { recursive: true });

  writeFileSync(VERSION_FILE, content, 'utf-8');

  console.log(`Version generated: ${version}`);
} catch (error) {
  // Fallback for non-git environments
  const content = `// Auto-generated by scripts/generate-version.ts
// DO NOT EDIT MANUALLY - Fallback for non-git environments

export const APP_VERSION = '${VERSION_PREFIX}-dev';
export const APP_VERSION_FULL = '${VERSION_PREFIX}-dev (no git info)';
export const APP_VERSION_PREFIX = '${VERSION_PREFIX}';
export const APP_GIT_HASH = 'unknown';
export const APP_COMMIT_COUNT = '0';
export const APP_BRANCH = 'unknown';
`;

  mkdirSync(join(__dirname, '../src/lib'), { recursive: true });
  writeFileSync(VERSION_FILE, content, 'utf-8');

  console.log('Version generated (fallback): v0.1-dev');
}
