/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=WorkerBindings worker/worker-configuration.d.ts` (hash: 4d93795608889cdd0e84669037a22a7d)
interface __BaseEnv_WorkerBindings {
	DB: D1Database;
	ASSETS: Fetcher;
	ENVIRONMENT: string;
	CF_ACCESS_TEAM_DOMAIN: string;
	CF_ACCESS_AUD: string;
	SITE_URL: string;
	LOCAL_USER_EMAIL: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface LocalEnv {
		DB: D1Database;
		ASSETS: Fetcher;
		ENVIRONMENT: string;
		CF_ACCESS_TEAM_DOMAIN: string;
		CF_ACCESS_AUD: string;
		SITE_URL: string;
		LOCAL_USER_EMAIL: string;
	}
	interface TestEnv {
		DB: D1Database;
		ASSETS: Fetcher;
		ENVIRONMENT: string;
		CF_ACCESS_TEAM_DOMAIN: string;
		CF_ACCESS_AUD: string;
		SITE_URL: string;
		LOCAL_USER_EMAIL: string;
	}
	interface Env extends __BaseEnv_WorkerBindings {}
}
interface WorkerBindings extends __BaseEnv_WorkerBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "CF_ACCESS_TEAM_DOMAIN" | "CF_ACCESS_AUD" | "SITE_URL" | "LOCAL_USER_EMAIL">> {}
}
